// chứa toàn bộ các action

module.exports = 
{
	SAVE_CONTACT: 'SAVE_CONTACT',
	RECEIVE_CONTACT: 'RECEIVE_CONTACT',
	EDIT_CONTACT: 'EDIT_CONTACT',
	REMOVE_CONTACT: 'REMOVE_CONTACT',
	UPDATE_CONTACT: 'UPDATE_CONTACT'
}